# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: BuildAndTest

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4
    - run: swift test --enable-code-coverage
    - uses: drekka/swift-coverage-action@develop
      with:
        show-all-files: true
