# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: BuildAndTest

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4
    # - uses: swift-actions/setup-swift@v1
    - run: swift test --enable-code-coverage # --show-code-coverage-path
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action/macos@v2
      if: always()
      with:
        files: .build/**/*.json
